-- Nickland Edusoft — one school's database, for Postgres.
--
--   GENERATED FILE. Do not edit by hand.
--   Regenerate with:  node scripts/schema-to-postgres.mjs
--
-- Rendered from the offline system's own schema (electron/db/database.js) by
-- building it in memory — CREATE statements and every migration, exactly as a
-- school's PC runs them — and reading the result back out. The online system
-- therefore holds the same school as the desktop does: same tables, same
-- columns, same constraints. A column added on the desktop appears here by
-- re-running the generator, not by somebody remembering to.
--
-- Applied INTO A PER-SCHOOL POSTGRES SCHEMA. Every school has its own, holding
-- this whole set of tables. That is what makes reusing the offline schema
-- honest: it has no school_id column and does not need one, and no query can
-- reach across two schools by forgetting a WHERE clause, because two schools
-- are never in the same table.
--
-- 81 tables, 41 indexes.

CREATE TABLE IF NOT EXISTS academic_years (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  start_date TEXT,
  end_date TEXT,
  is_current BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  audience TEXT DEFAULT 'all',
  target_student_id BIGINT,
  is_active BIGINT DEFAULT 1,
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS api_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash TEXT UNIQUE NOT NULL,
  subject_type TEXT NOT NULL,
  subject_id BIGINT NOT NULL,
  device_name TEXT,
  platform TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_used_at TEXT,
  expires_at TEXT,
  revoked BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS assessment_columns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_group_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  term_id BIGINT NOT NULL,
  assessment_type TEXT NOT NULL DEFAULT 'Assignment',
  max_marks DOUBLE PRECISION NOT NULL DEFAULT 10,
  display_order BIGINT DEFAULT 0,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS assessment_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_column_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  marks DOUBLE PRECISION DEFAULT 0,
  UNIQUE (assessment_column_id, student_id)
);
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id BIGINT,
  action TEXT NOT NULL,
  user_id BIGINT,
  justification TEXT,
  before_data TEXT,
  after_data TEXT,
  severity TEXT DEFAULT 'normal',
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS bill_line_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_bill_id BIGINT NOT NULL,
  item_number BIGINT DEFAULT 0,
  description TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_arrear BIGINT DEFAULT 0,
  arrear_from_term_id BIGINT,
  charge_type TEXT NOT NULL DEFAULT 'fees',
  source_template_id BIGINT,
  added_at TEXT,
  added_by BIGINT
);
CREATE TABLE IF NOT EXISTS books_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  student_books_id BIGINT,
  amount DOUBLE PRECISION NOT NULL,
  payment_date TEXT NOT NULL,
  payment_method TEXT DEFAULT 'Cash',
  reference TEXT,
  receipt_number TEXT UNIQUE,
  received_by BIGINT,
  notes TEXT,
  is_reversed BIGINT DEFAULT 0,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS budget_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id BIGINT NOT NULL,
  item_type TEXT NOT NULL DEFAULT 'expense',
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  projected_amount DOUBLE PRECISION DEFAULT 0,
  actual_amount DOUBLE PRECISION DEFAULT 0,
  notes TEXT,
  display_order BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  budget_type TEXT NOT NULL DEFAULT 'term',
  academic_year_id BIGINT,
  term_id BIGINT,
  period_label TEXT,
  start_date TEXT,
  end_date TEXT,
  notes TEXT,
  status TEXT DEFAULT 'draft',
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS canteen_day_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'unpaid',
  payment_id BIGINT,
  UNIQUE (student_id, date)
);
CREATE TABLE IF NOT EXISTS canteen_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  payment_date TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  days_covered BIGINT NOT NULL,
  start_date TEXT,
  end_date TEXT,
  received_by BIGINT,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  term_id BIGINT,
  daily_rate DOUBLE PRECISION
);
CREATE TABLE IF NOT EXISTS class_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  short_code TEXT,
  level_category TEXT NOT NULL,
  level_order BIGINT NOT NULL,
  section TEXT,
  parent_class_id BIGINT,
  capacity BIGINT,
  is_active BIGINT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS class_score_components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_group_id BIGINT NOT NULL,
  term_id BIGINT NOT NULL,
  component_name TEXT NOT NULL,
  max_marks DOUBLE PRECISION NOT NULL,
  display_order BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS class_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_group_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  UNIQUE (class_group_id, subject_id)
);
CREATE TABLE IF NOT EXISTS designation_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  designation_id BIGINT NOT NULL,
  module TEXT NOT NULL,
  can_view BIGINT DEFAULT 0,
  can_create BIGINT DEFAULT 0,
  can_edit BIGINT DEFAULT 0,
  can_delete BIGINT DEFAULT 0,
  UNIQUE (designation_id, module)
);
CREATE TABLE IF NOT EXISTS designations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  is_system BIGINT DEFAULT 0,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS exam_papers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  class_group_id BIGINT,
  subject_id BIGINT,
  term_id BIGINT,
  exam_type TEXT DEFAULT 'end_of_term',
  total_marks DOUBLE PRECISION,
  duration_minutes BIGINT,
  instructions TEXT,
  status TEXT DEFAULT 'draft',
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS exam_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_paper_id BIGINT,
  section_id BIGINT,
  class_group_id BIGINT,
  subject_id BIGINT,
  question_type TEXT NOT NULL DEFAULT 'essay',
  question_text TEXT NOT NULL,
  question_image_path TEXT,
  marks DOUBLE PRECISION DEFAULT 1,
  difficulty TEXT DEFAULT 'medium',
  option_a TEXT,
  option_b TEXT,
  option_c TEXT,
  option_d TEXT,
  correct_option TEXT,
  model_answer TEXT,
  display_order BIGINT DEFAULT 0,
  in_question_bank BIGINT DEFAULT 1,
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS exam_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_paper_id BIGINT NOT NULL,
  section_label TEXT NOT NULL,
  instructions TEXT,
  marks_allocation DOUBLE PRECISION,
  display_order BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS expense_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_number TEXT UNIQUE,
  category TEXT NOT NULL,
  subcategory TEXT,
  amount DOUBLE PRECISION NOT NULL,
  payee_name TEXT,
  paid_to TEXT,
  description TEXT NOT NULL,
  payment_method TEXT DEFAULT 'Cash',
  reference TEXT,
  transaction_date TEXT NOT NULL,
  date TEXT,
  linked_salary_id BIGINT,
  academic_year_id BIGINT,
  term_id BIGINT,
  approved_by BIGINT,
  recorded_by BIGINT,
  is_auto BIGINT DEFAULT 0,
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS fee_line_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fee_template_id BIGINT NOT NULL,
  item_number BIGINT,
  description TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_optional BIGINT DEFAULT 0,
  category TEXT
);
CREATE TABLE IF NOT EXISTS fee_template_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL,
  part TEXT DEFAULT 'A',
  item_name TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_optional BIGINT DEFAULT 0,
  display_order BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS fee_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  class_group_id BIGINT,
  term_id BIGINT,
  is_active BIGINT DEFAULT 1,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  bill_type TEXT NOT NULL DEFAULT 'school_fees',
  academic_year_id BIGINT,
  notes TEXT,
  copied_from_template_id BIGINT
);
CREATE TABLE IF NOT EXISTS grading_bands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  min_score DOUBLE PRECISION NOT NULL,
  max_score DOUBLE PRECISION NOT NULL,
  remark TEXT NOT NULL,
  display_order BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS homework (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_group_id BIGINT NOT NULL,
  subject_id BIGINT,
  teacher_id BIGINT,
  title TEXT NOT NULL,
  description TEXT,
  due_date TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  term_id BIGINT,
  max_marks DOUBLE PRECISION,
  assessment_column_id BIGINT,
  assigned_date TEXT,
  status TEXT DEFAULT 'published'
);
CREATE TABLE IF NOT EXISTS homework_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  marks DOUBLE PRECISION,
  remarks TEXT,
  submitted_at TEXT,
  marked_at TEXT,
  UNIQUE (homework_id, student_id)
);
CREATE TABLE IF NOT EXISTS income_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number TEXT UNIQUE,
  category TEXT NOT NULL,
  subcategory TEXT,
  amount DOUBLE PRECISION NOT NULL,
  payer_name TEXT,
  description TEXT,
  payment_method TEXT DEFAULT 'Cash',
  reference TEXT,
  transaction_date TEXT NOT NULL,
  date TEXT,
  source TEXT,
  linked_payment_id BIGINT,
  linked_canteen_payment_id BIGINT,
  academic_year_id BIGINT,
  term_id BIGINT,
  recorded_by BIGINT,
  student_id BIGINT,
  staff_id BIGINT,
  is_auto BIGINT DEFAULT 0,
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS inventory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  unit TEXT DEFAULT 'piece',
  unit_cost DOUBLE PRECISION DEFAULT 0,
  quantity_on_hand DOUBLE PRECISION DEFAULT 0,
  reorder_level DOUBLE PRECISION DEFAULT 0,
  location TEXT,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_item_id BIGINT NOT NULL,
  movement_type TEXT NOT NULL,
  quantity DOUBLE PRECISION NOT NULL,
  unit_cost DOUBLE PRECISION DEFAULT 0,
  total_cost DOUBLE PRECISION DEFAULT 0,
  movement_date TEXT NOT NULL,
  reference TEXT,
  linked_expense_id BIGINT,
  recorded_by BIGINT,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  leave_type TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  days_requested BIGINT NOT NULL,
  justification TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  reviewed_by BIGINT,
  reviewed_at TEXT,
  reviewer_notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS lesson_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  class_group_id BIGINT,
  subject_id BIGINT,
  term_id BIGINT,
  week_number BIGINT,
  lesson_date TEXT,
  duration_minutes BIGINT,
  topic TEXT NOT NULL,
  sub_topic TEXT,
  references_text TEXT,
  tlms TEXT,
  objectives TEXT,
  rpk TEXT,
  introduction TEXT,
  presentation TEXT,
  activity TEXT,
  evaluation TEXT,
  closure TEXT,
  assignment TEXT,
  remarks TEXT,
  status TEXT DEFAULT 'draft',
  reviewed_by BIGINT,
  reviewed_at TEXT,
  review_comments TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS login_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  logged_in_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  logged_out_at TEXT,
  ip_address TEXT
);
CREATE TABLE IF NOT EXISTS message_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE,
  parent_id BIGINT NOT NULL,
  student_id BIGINT,
  subject TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_message_at TEXT,
  last_sender TEXT,
  parent_unread BIGINT NOT NULL DEFAULT 0,
  staff_unread BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE,
  thread_id BIGINT NOT NULL,
  sender_type TEXT NOT NULL,
  sender_id BIGINT,
  sender_name TEXT,
  body TEXT NOT NULL,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS notification_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel TEXT NOT NULL,
  recipient_type TEXT,
  recipient_role TEXT,
  recipient_id BIGINT,
  recipient_name TEXT,
  recipient_contact TEXT,
  message_body TEXT,
  attachment_paths TEXT,
  sent_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  delivery_status TEXT DEFAULT 'pending',
  api_response TEXT,
  template_used TEXT,
  cost DOUBLE PRECISION,
  units_used BIGINT,
  sent_by BIGINT
);
CREATE TABLE IF NOT EXISTS notification_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  channel TEXT NOT NULL,
  body TEXT NOT NULL,
  category TEXT,
  is_active BIGINT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS parent_students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  relationship TEXT,
  UNIQUE (parent_id, student_id)
);
CREATE TABLE IF NOT EXISTS parents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  password_hash TEXT,
  is_active BIGINT DEFAULT 1,
  must_change_password BIGINT DEFAULT 0,
  last_login TEXT,
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS password_reset_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  reason TEXT,
  requested_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  requested_from TEXT,
  decided_by BIGINT,
  decided_at TEXT,
  decision_note TEXT,
  claim_hash TEXT,
  claim_expires_at TEXT,
  used_at TEXT
);
CREATE TABLE IF NOT EXISTS payment_intents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT,
  student_id BIGINT NOT NULL,
  parent_id BIGINT,
  term_id BIGINT,
  amount DOUBLE PRECISION NOT NULL,
  channel TEXT DEFAULT 'mobile',
  reference TEXT,
  notes TEXT,
  status TEXT DEFAULT 'pending',
  payment_id BIGINT,
  acknowledged_by BIGINT,
  acknowledged_at TEXT,
  reject_reason TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  gateway TEXT,
  gateway_reference TEXT,
  authorization_url TEXT,
  gateway_status TEXT,
  currency TEXT,
  email TEXT
);
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  student_bill_id BIGINT,
  term_id BIGINT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  payment_date TEXT NOT NULL,
  payment_method TEXT DEFAULT 'Cash',
  reference TEXT,
  receipt_number TEXT UNIQUE,
  received_by BIGINT,
  notes TEXT,
  is_reversed BIGINT DEFAULT 0,
  reversed_by BIGINT,
  reversal_reason TEXT,
  reversed_at TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  start_date TEXT,
  target_end_date TEXT,
  actual_end_date TEXT,
  budget DOUBLE PRECISION DEFAULT 0,
  spent DOUBLE PRECISION DEFAULT 0,
  status TEXT DEFAULT 'Planning',
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS receipt_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_type TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  file_path TEXT NOT NULL,
  is_default BIGINT DEFAULT 0,
  is_active BIGINT DEFAULT 1,
  uploaded_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number TEXT,
  receipt_type TEXT NOT NULL DEFAULT 'fees',
  source TEXT,
  source_id BIGINT,
  student_id BIGINT,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  payment_method TEXT,
  term_id BIGINT,
  academic_year_id BIGINT,
  payer_name TEXT,
  recipient_contact TEXT,
  issued_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  issued_by BIGINT,
  pdf_path TEXT,
  delivery_status TEXT DEFAULT 'issued',
  delivered_channels TEXT
);
CREATE TABLE IF NOT EXISTS school_calendar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT UNIQUE NOT NULL,
  day_type TEXT NOT NULL DEFAULT 'school_day',
  label TEXT,
  term_id BIGINT
);
CREATE TABLE IF NOT EXISTS scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  term_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  class_score DOUBLE PRECISION DEFAULT 0,
  exam_score DOUBLE PRECISION DEFAULT 0,
  total_score DOUBLE PRECISION DEFAULT 0,
  grade_remark TEXT,
  UNIQUE (student_id, term_id, subject_id)
);
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  category TEXT,
  description TEXT
);
CREATE TABLE IF NOT EXISTS staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_number TEXT UNIQUE,
  surname TEXT,
  first_name TEXT,
  other_names TEXT,
  gender TEXT,
  date_of_birth TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  role TEXT NOT NULL,
  designation_id BIGINT,
  status TEXT DEFAULT 'Active',
  qualification TEXT,
  specialization TEXT,
  bank_account TEXT,
  bank_name TEXT,
  ssnit_number TEXT,
  ssnit_enrolled BIGINT DEFAULT 0,
  hire_date TEXT,
  stop_date TEXT,
  photo_path TEXT,
  base_salary DOUBLE PRECISION DEFAULT 0,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS staff_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  activity_date TEXT NOT NULL,
  activity_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  duration_minutes BIGINT,
  location TEXT,
  related_class_id BIGINT,
  hours_contributed DOUBLE PRECISION,
  acknowledged_by BIGINT,
  acknowledged_at TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS staff_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  class_group_id BIGINT,
  subject_id BIGINT,
  term_id BIGINT,
  is_class_teacher BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS staff_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  clock_in TEXT,
  clock_out TEXT,
  status TEXT DEFAULT 'present',
  notes TEXT,
  UNIQUE (staff_id, date)
);
CREATE TABLE IF NOT EXISTS staff_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  doc_type TEXT NOT NULL,
  title TEXT NOT NULL,
  file_path TEXT,
  issue_date TEXT,
  expiry_date TEXT,
  notes TEXT,
  uploaded_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS staff_medical (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  blood_group TEXT,
  known_conditions TEXT,
  allergies TEXT,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  emergency_contact_relation TEXT,
  nhis_number TEXT,
  notes TEXT,
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS staff_performance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  review_period TEXT NOT NULL,
  reviewer_id BIGINT,
  overall_rating BIGINT,
  teaching_quality BIGINT,
  punctuality BIGINT,
  professionalism BIGINT,
  comments TEXT,
  reviewed_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS staff_salaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  month BIGINT NOT NULL,
  year BIGINT NOT NULL,
  gross_salary DOUBLE PRECISION DEFAULT 0,
  extra_pay DOUBLE PRECISION DEFAULT 0,
  extra_pay_description TEXT,
  arrear_brought_forward DOUBLE PRECISION DEFAULT 0,
  ssnit_worker DOUBLE PRECISION DEFAULT 0,
  ssnit_employer DOUBLE PRECISION DEFAULT 0,
  paye_tax DOUBLE PRECISION DEFAULT 0,
  other_deductions DOUBLE PRECISION DEFAULT 0,
  other_deductions_description TEXT,
  net_salary DOUBLE PRECISION DEFAULT 0,
  actual_amount_paid DOUBLE PRECISION DEFAULT 0,
  carry_over_to_next DOUBLE PRECISION DEFAULT 0,
  payment_date TEXT,
  payment_method TEXT,
  payment_reference TEXT,
  is_paid BIGINT DEFAULT 0,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (staff_id, month, year)
);
CREATE TABLE IF NOT EXISTS staff_training (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  provider TEXT,
  start_date TEXT,
  end_date TEXT,
  certificate_path TEXT,
  notes TEXT
);
CREATE TABLE IF NOT EXISTS student_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'present',
  marked_by BIGINT,
  term_id BIGINT,
  notes TEXT,
  UNIQUE (student_id, date)
);
CREATE TABLE IF NOT EXISTS student_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  term_id BIGINT NOT NULL,
  template_id BIGINT,
  total_billed DOUBLE PRECISION DEFAULT 0,
  total_paid DOUBLE PRECISION DEFAULT 0,
  balance DOUBLE PRECISION DEFAULT 0,
  arrears_from_prev DOUBLE PRECISION DEFAULT 0,
  books_total DOUBLE PRECISION DEFAULT 0,
  books_paid DOUBLE PRECISION DEFAULT 0,
  books_arrears DOUBLE PRECISION DEFAULT 0,
  discount_amount DOUBLE PRECISION DEFAULT 0,
  discount_reason TEXT,
  generated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  status TEXT NOT NULL DEFAULT 'active',
  supplementary_total DOUBLE PRECISION DEFAULT 0,
  voided_at TEXT,
  voided_by BIGINT,
  void_reason TEXT,
  UNIQUE (student_id, term_id)
);
CREATE TABLE IF NOT EXISTS student_books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  academic_year_id BIGINT NOT NULL,
  class_group_id BIGINT,
  total_amount DOUBLE PRECISION DEFAULT 0,
  total_paid DOUBLE PRECISION DEFAULT 0,
  balance DOUBLE PRECISION DEFAULT 0,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (student_id, academic_year_id)
);
CREATE TABLE IF NOT EXISTS student_books_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_books_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  display_order BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS student_class_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  class_group_id BIGINT NOT NULL,
  academic_year_id BIGINT NOT NULL,
  enrolled_date TEXT
);
CREATE TABLE IF NOT EXISTS student_discounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  discount_type TEXT NOT NULL DEFAULT 'percent',
  discount_value DOUBLE PRECISION NOT NULL DEFAULT 0,
  reason TEXT NOT NULL,
  applies_to TEXT DEFAULT 'fees',
  is_active BIGINT DEFAULT 1,
  effective_from TEXT,
  effective_to TEXT,
  granted_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS student_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  date TEXT,
  recorded_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS student_term_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  term_id BIGINT NOT NULL,
  class_group_id BIGINT,
  total_score_all DOUBLE PRECISION DEFAULT 0,
  average_score DOUBLE PRECISION DEFAULT 0,
  class_rank BIGINT,
  number_on_roll BIGINT,
  conduct_traits TEXT,
  learner_interests TEXT,
  learner_talents TEXT,
  teacher_remarks TEXT,
  days_present BIGINT,
  total_days BIGINT,
  promoted_to TEXT,
  UNIQUE (student_id, term_id)
);
CREATE TABLE IF NOT EXISTS student_transport (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL UNIQUE,
  route_id BIGINT NOT NULL,
  stop_id BIGINT,
  direction TEXT NOT NULL DEFAULT 'both',
  fee_override DOUBLE PRECISION,
  start_date TEXT,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  index_number TEXT UNIQUE,
  admission_year BIGINT,
  roll_number BIGINT UNIQUE,
  surname TEXT,
  first_name TEXT,
  other_names TEXT,
  gender TEXT,
  denomination TEXT,
  age BIGINT,
  date_of_birth TEXT,
  place_of_birth TEXT,
  place_of_residence TEXT,
  street_address TEXT,
  house_number TEXT,
  digital_address TEXT,
  nhis_number TEXT,
  father_name TEXT,
  father_contact TEXT,
  mother_name TEXT,
  mother_contact TEXT,
  guardian_name TEXT,
  guardian_contact TEXT,
  current_class_id BIGINT,
  status TEXT DEFAULT 'Active',
  inactive_reason TEXT,
  photo_path TEXT,
  admission_date TEXT,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  father_email TEXT,
  mother_email TEXT,
  guardian_email TEXT
);
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT,
  class_weight_pct DOUBLE PRECISION DEFAULT 40,
  exam_weight_pct DOUBLE PRECISION DEFAULT 60,
  is_active BIGINT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS sync_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT,
  entity_type TEXT NOT NULL,
  entity_key TEXT,
  op TEXT DEFAULT 'upsert',
  payload_json TEXT,
  version BIGINT DEFAULT 1,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  synced_at TEXT,
  attempts BIGINT DEFAULT 0,
  last_error TEXT,
  next_attempt_at TEXT,
  dead BIGINT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS sync_versions (
  entity_key TEXT PRIMARY KEY,
  version BIGINT NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS system_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL DEFAULT 'info',
  source TEXT,
  message TEXT NOT NULL,
  detail TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year_id BIGINT NOT NULL,
  term_number BIGINT NOT NULL,
  label TEXT NOT NULL,
  start_date TEXT,
  end_date TEXT,
  is_current BIGINT DEFAULT 0,
  vacation_date TEXT,
  reopening_date TEXT
);
CREATE TABLE IF NOT EXISTS timetable_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_group_id BIGINT NOT NULL,
  day_of_week BIGINT NOT NULL,
  period_id BIGINT NOT NULL,
  subject_id BIGINT,
  teacher_id BIGINT,
  notes TEXT,
  UNIQUE (class_group_id, day_of_week, period_id)
);
CREATE TABLE IF NOT EXISTS timetable_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  display_order BIGINT NOT NULL DEFAULT 0,
  is_break BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS transport_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  route_id BIGINT,
  term_id BIGINT,
  amount DOUBLE PRECISION NOT NULL,
  payment_date TEXT NOT NULL,
  payment_method TEXT DEFAULT 'Cash',
  received_by BIGINT,
  notes TEXT,
  receipt_number TEXT UNIQUE,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS transport_routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  vehicle_number TEXT,
  driver_name TEXT,
  driver_phone TEXT,
  capacity BIGINT,
  fee_per_term DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS transport_stops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  pickup_time TEXT,
  dropoff_time TEXT,
  display_order BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS user_permission_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  module TEXT NOT NULL,
  can_view BIGINT DEFAULT 0,
  can_create BIGINT DEFAULT 0,
  can_edit BIGINT DEFAULT 0,
  can_delete BIGINT DEFAULT 0,
  granted_by BIGINT,
  granted_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (user_id, module)
);
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  full_name TEXT NOT NULL,
  designation_id BIGINT,
  staff_id BIGINT,
  is_active BIGINT DEFAULT 1,
  must_change_password BIGINT DEFAULT 0,
  last_login TEXT,
  photo_path TEXT,
  created_by BIGINT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS welfare_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_type TEXT NOT NULL,
  beneficiary_name TEXT,
  student_id BIGINT,
  staff_id BIGINT,
  welfare_type TEXT NOT NULL,
  amount DOUBLE PRECISION DEFAULT 0,
  description TEXT,
  approved_by BIGINT,
  approved_date TEXT,
  term_id BIGINT
);
CREATE TABLE IF NOT EXISTS workbook_import_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_key TEXT NOT NULL UNIQUE,
  sheet TEXT NOT NULL,
  target_table TEXT,
  target_id BIGINT,
  amount DOUBLE PRECISION,
  summary TEXT,
  source_file TEXT,
  imported_by BIGINT,
  imported_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

-- ── how the school ties together ──
-- Attached after the tables so the order they were created in cannot
-- matter, and so a reference added later needs no reordering.
DO $$ BEGIN
  ALTER TABLE announcements ADD CONSTRAINT announcements_fk_1 FOREIGN KEY (target_student_id) REFERENCES students(id);
  ALTER TABLE assessment_columns ADD CONSTRAINT assessment_columns_fk_1 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE assessment_columns ADD CONSTRAINT assessment_columns_fk_2 FOREIGN KEY (subject_id) REFERENCES subjects(id);
  ALTER TABLE assessment_columns ADD CONSTRAINT assessment_columns_fk_3 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE assessment_scores ADD CONSTRAINT assessment_scores_fk_1 FOREIGN KEY (assessment_column_id) REFERENCES assessment_columns(id) ON DELETE CASCADE;
  ALTER TABLE assessment_scores ADD CONSTRAINT assessment_scores_fk_2 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE audit_log ADD CONSTRAINT audit_log_fk_1 FOREIGN KEY (user_id) REFERENCES users(id);
  ALTER TABLE bill_line_items ADD CONSTRAINT bill_line_items_fk_1 FOREIGN KEY (student_bill_id) REFERENCES student_bills(id) ON DELETE CASCADE;
  ALTER TABLE bill_line_items ADD CONSTRAINT bill_line_items_fk_2 FOREIGN KEY (arrear_from_term_id) REFERENCES terms(id);
  ALTER TABLE books_payments ADD CONSTRAINT books_payments_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE books_payments ADD CONSTRAINT books_payments_fk_2 FOREIGN KEY (student_books_id) REFERENCES student_books(id);
  ALTER TABLE books_payments ADD CONSTRAINT books_payments_fk_3 FOREIGN KEY (received_by) REFERENCES users(id);
  ALTER TABLE budget_items ADD CONSTRAINT budget_items_fk_1 FOREIGN KEY (budget_id) REFERENCES budgets(id) ON DELETE CASCADE;
  ALTER TABLE budgets ADD CONSTRAINT budgets_fk_1 FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
  ALTER TABLE budgets ADD CONSTRAINT budgets_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE budgets ADD CONSTRAINT budgets_fk_3 FOREIGN KEY (created_by) REFERENCES users(id);
  ALTER TABLE canteen_day_status ADD CONSTRAINT canteen_day_status_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE canteen_day_status ADD CONSTRAINT canteen_day_status_fk_2 FOREIGN KEY (payment_id) REFERENCES canteen_payments(id);
  ALTER TABLE canteen_payments ADD CONSTRAINT canteen_payments_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE canteen_payments ADD CONSTRAINT canteen_payments_fk_2 FOREIGN KEY (received_by) REFERENCES users(id);
  ALTER TABLE class_groups ADD CONSTRAINT class_groups_fk_1 FOREIGN KEY (parent_class_id) REFERENCES class_groups(id);
  ALTER TABLE class_score_components ADD CONSTRAINT class_score_components_fk_1 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE class_score_components ADD CONSTRAINT class_score_components_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE class_subjects ADD CONSTRAINT class_subjects_fk_1 FOREIGN KEY (class_group_id) REFERENCES class_groups(id) ON DELETE CASCADE;
  ALTER TABLE class_subjects ADD CONSTRAINT class_subjects_fk_2 FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE;
  ALTER TABLE designation_permissions ADD CONSTRAINT designation_permissions_fk_1 FOREIGN KEY (designation_id) REFERENCES designations(id) ON DELETE CASCADE;
  ALTER TABLE exam_papers ADD CONSTRAINT exam_papers_fk_1 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE exam_papers ADD CONSTRAINT exam_papers_fk_2 FOREIGN KEY (subject_id) REFERENCES subjects(id);
  ALTER TABLE exam_papers ADD CONSTRAINT exam_papers_fk_3 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE exam_papers ADD CONSTRAINT exam_papers_fk_4 FOREIGN KEY (created_by) REFERENCES users(id);
  ALTER TABLE exam_questions ADD CONSTRAINT exam_questions_fk_1 FOREIGN KEY (exam_paper_id) REFERENCES exam_papers(id) ON DELETE SET NULL;
  ALTER TABLE exam_questions ADD CONSTRAINT exam_questions_fk_2 FOREIGN KEY (section_id) REFERENCES exam_sections(id) ON DELETE SET NULL;
  ALTER TABLE exam_questions ADD CONSTRAINT exam_questions_fk_3 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE exam_questions ADD CONSTRAINT exam_questions_fk_4 FOREIGN KEY (subject_id) REFERENCES subjects(id);
  ALTER TABLE exam_questions ADD CONSTRAINT exam_questions_fk_5 FOREIGN KEY (created_by) REFERENCES users(id);
  ALTER TABLE exam_sections ADD CONSTRAINT exam_sections_fk_1 FOREIGN KEY (exam_paper_id) REFERENCES exam_papers(id) ON DELETE CASCADE;
  ALTER TABLE expense_records ADD CONSTRAINT expense_records_fk_1 FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
  ALTER TABLE expense_records ADD CONSTRAINT expense_records_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE expense_records ADD CONSTRAINT expense_records_fk_3 FOREIGN KEY (approved_by) REFERENCES users(id);
  ALTER TABLE expense_records ADD CONSTRAINT expense_records_fk_4 FOREIGN KEY (recorded_by) REFERENCES users(id);
  ALTER TABLE fee_line_items ADD CONSTRAINT fee_line_items_fk_1 FOREIGN KEY (fee_template_id) REFERENCES fee_templates(id) ON DELETE CASCADE;
  ALTER TABLE fee_template_items ADD CONSTRAINT fee_template_items_fk_1 FOREIGN KEY (template_id) REFERENCES fee_templates(id) ON DELETE CASCADE;
  ALTER TABLE fee_templates ADD CONSTRAINT fee_templates_fk_1 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE fee_templates ADD CONSTRAINT fee_templates_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE homework_submissions ADD CONSTRAINT homework_submissions_fk_1 FOREIGN KEY (homework_id) REFERENCES homework(id) ON DELETE CASCADE;
  ALTER TABLE homework_submissions ADD CONSTRAINT homework_submissions_fk_2 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE income_records ADD CONSTRAINT income_records_fk_1 FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
  ALTER TABLE income_records ADD CONSTRAINT income_records_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE income_records ADD CONSTRAINT income_records_fk_3 FOREIGN KEY (recorded_by) REFERENCES users(id);
  ALTER TABLE income_records ADD CONSTRAINT income_records_fk_4 FOREIGN KEY (student_id) REFERENCES students(id);
  ALTER TABLE income_records ADD CONSTRAINT income_records_fk_5 FOREIGN KEY (staff_id) REFERENCES staff(id);
  ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_fk_1 FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE;
  ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_fk_2 FOREIGN KEY (linked_expense_id) REFERENCES expense_records(id);
  ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_fk_3 FOREIGN KEY (recorded_by) REFERENCES users(id);
  ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_fk_2 FOREIGN KEY (reviewed_by) REFERENCES users(id);
  ALTER TABLE lesson_notes ADD CONSTRAINT lesson_notes_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE lesson_notes ADD CONSTRAINT lesson_notes_fk_2 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE lesson_notes ADD CONSTRAINT lesson_notes_fk_3 FOREIGN KEY (subject_id) REFERENCES subjects(id);
  ALTER TABLE lesson_notes ADD CONSTRAINT lesson_notes_fk_4 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE lesson_notes ADD CONSTRAINT lesson_notes_fk_5 FOREIGN KEY (reviewed_by) REFERENCES users(id);
  ALTER TABLE login_sessions ADD CONSTRAINT login_sessions_fk_1 FOREIGN KEY (user_id) REFERENCES users(id);
  ALTER TABLE notification_log ADD CONSTRAINT notification_log_fk_1 FOREIGN KEY (sent_by) REFERENCES users(id);
  ALTER TABLE parent_students ADD CONSTRAINT parent_students_fk_1 FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;
  ALTER TABLE parent_students ADD CONSTRAINT parent_students_fk_2 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE password_reset_requests ADD CONSTRAINT password_reset_requests_fk_1 FOREIGN KEY (user_id) REFERENCES users(id);
  ALTER TABLE password_reset_requests ADD CONSTRAINT password_reset_requests_fk_2 FOREIGN KEY (decided_by) REFERENCES users(id);
  ALTER TABLE payment_intents ADD CONSTRAINT payment_intents_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE payment_intents ADD CONSTRAINT payment_intents_fk_2 FOREIGN KEY (parent_id) REFERENCES parents(id);
  ALTER TABLE payments ADD CONSTRAINT payments_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE payments ADD CONSTRAINT payments_fk_2 FOREIGN KEY (student_bill_id) REFERENCES student_bills(id);
  ALTER TABLE payments ADD CONSTRAINT payments_fk_3 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE payments ADD CONSTRAINT payments_fk_4 FOREIGN KEY (received_by) REFERENCES users(id);
  ALTER TABLE receipt_templates ADD CONSTRAINT receipt_templates_fk_1 FOREIGN KEY (uploaded_by) REFERENCES users(id);
  ALTER TABLE school_calendar ADD CONSTRAINT school_calendar_fk_1 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE scores ADD CONSTRAINT scores_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE scores ADD CONSTRAINT scores_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE scores ADD CONSTRAINT scores_fk_3 FOREIGN KEY (subject_id) REFERENCES subjects(id);
  ALTER TABLE staff ADD CONSTRAINT staff_fk_1 FOREIGN KEY (designation_id) REFERENCES designations(id);
  ALTER TABLE staff_activities ADD CONSTRAINT staff_activities_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE staff_activities ADD CONSTRAINT staff_activities_fk_2 FOREIGN KEY (related_class_id) REFERENCES class_groups(id);
  ALTER TABLE staff_activities ADD CONSTRAINT staff_activities_fk_3 FOREIGN KEY (acknowledged_by) REFERENCES users(id);
  ALTER TABLE staff_assignments ADD CONSTRAINT staff_assignments_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE staff_assignments ADD CONSTRAINT staff_assignments_fk_2 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE staff_assignments ADD CONSTRAINT staff_assignments_fk_3 FOREIGN KEY (subject_id) REFERENCES subjects(id);
  ALTER TABLE staff_assignments ADD CONSTRAINT staff_assignments_fk_4 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE staff_attendance ADD CONSTRAINT staff_attendance_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE staff_documents ADD CONSTRAINT staff_documents_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE staff_medical ADD CONSTRAINT staff_medical_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE staff_performance ADD CONSTRAINT staff_performance_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE staff_performance ADD CONSTRAINT staff_performance_fk_2 FOREIGN KEY (reviewer_id) REFERENCES users(id);
  ALTER TABLE staff_salaries ADD CONSTRAINT staff_salaries_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE staff_training ADD CONSTRAINT staff_training_fk_1 FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
  ALTER TABLE student_attendance ADD CONSTRAINT student_attendance_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_attendance ADD CONSTRAINT student_attendance_fk_2 FOREIGN KEY (marked_by) REFERENCES users(id);
  ALTER TABLE student_attendance ADD CONSTRAINT student_attendance_fk_3 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE student_bills ADD CONSTRAINT student_bills_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_bills ADD CONSTRAINT student_bills_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE student_bills ADD CONSTRAINT student_bills_fk_3 FOREIGN KEY (template_id) REFERENCES fee_templates(id);
  ALTER TABLE student_books ADD CONSTRAINT student_books_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_books ADD CONSTRAINT student_books_fk_2 FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
  ALTER TABLE student_books ADD CONSTRAINT student_books_fk_3 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE student_books_items ADD CONSTRAINT student_books_items_fk_1 FOREIGN KEY (student_books_id) REFERENCES student_books(id) ON DELETE CASCADE;
  ALTER TABLE student_class_history ADD CONSTRAINT student_class_history_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_class_history ADD CONSTRAINT student_class_history_fk_2 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE student_class_history ADD CONSTRAINT student_class_history_fk_3 FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
  ALTER TABLE student_discounts ADD CONSTRAINT student_discounts_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_discounts ADD CONSTRAINT student_discounts_fk_2 FOREIGN KEY (granted_by) REFERENCES users(id);
  ALTER TABLE student_events ADD CONSTRAINT student_events_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_events ADD CONSTRAINT student_events_fk_2 FOREIGN KEY (recorded_by) REFERENCES users(id);
  ALTER TABLE student_term_summary ADD CONSTRAINT student_term_summary_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_term_summary ADD CONSTRAINT student_term_summary_fk_2 FOREIGN KEY (term_id) REFERENCES terms(id);
  ALTER TABLE student_term_summary ADD CONSTRAINT student_term_summary_fk_3 FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
  ALTER TABLE student_transport ADD CONSTRAINT student_transport_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE student_transport ADD CONSTRAINT student_transport_fk_2 FOREIGN KEY (route_id) REFERENCES transport_routes(id);
  ALTER TABLE student_transport ADD CONSTRAINT student_transport_fk_3 FOREIGN KEY (stop_id) REFERENCES transport_stops(id);
  ALTER TABLE students ADD CONSTRAINT students_fk_1 FOREIGN KEY (current_class_id) REFERENCES class_groups(id);
  ALTER TABLE terms ADD CONSTRAINT terms_fk_1 FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
  ALTER TABLE transport_payments ADD CONSTRAINT transport_payments_fk_1 FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
  ALTER TABLE transport_stops ADD CONSTRAINT transport_stops_fk_1 FOREIGN KEY (route_id) REFERENCES transport_routes(id) ON DELETE CASCADE;
  ALTER TABLE user_permission_overrides ADD CONSTRAINT user_permission_overrides_fk_1 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  ALTER TABLE users ADD CONSTRAINT users_fk_1 FOREIGN KEY (designation_id) REFERENCES designations(id);
  ALTER TABLE users ADD CONSTRAINT users_fk_2 FOREIGN KEY (staff_id) REFERENCES staff(id);
  ALTER TABLE welfare_records ADD CONSTRAINT welfare_records_fk_1 FOREIGN KEY (student_id) REFERENCES students(id);
  ALTER TABLE welfare_records ADD CONSTRAINT welfare_records_fk_2 FOREIGN KEY (staff_id) REFERENCES staff(id);
  ALTER TABLE welfare_records ADD CONSTRAINT welfare_records_fk_3 FOREIGN KEY (approved_by) REFERENCES users(id);
  ALTER TABLE welfare_records ADD CONSTRAINT welfare_records_fk_4 FOREIGN KEY (term_id) REFERENCES terms(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── indexes ──
CREATE INDEX IF NOT EXISTS idx_api_tokens_subject ON api_tokens(subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_bill_items_type ON bill_line_items(student_bill_id, charge_type);
CREATE INDEX IF NOT EXISTS idx_bills_status ON student_bills(status, term_id);
CREATE INDEX IF NOT EXISTS idx_bills_student_term ON student_bills(student_id, term_id);
CREATE INDEX IF NOT EXISTS idx_canteen_day_status ON canteen_day_status(student_id, date);
CREATE INDEX IF NOT EXISTS idx_expense_linked_salary ON expense_records(linked_salary_id);
CREATE INDEX IF NOT EXISTS idx_expense_term ON expense_records(term_id);
CREATE INDEX IF NOT EXISTS idx_expense_txn_date ON expense_records(transaction_date);
CREATE INDEX IF NOT EXISTS idx_homework_class ON homework(class_group_id, due_date);
CREATE INDEX IF NOT EXISTS idx_homework_term   ON homework(term_id, class_group_id);
CREATE INDEX IF NOT EXISTS idx_hw_sub_homework ON homework_submissions(homework_id);
CREATE INDEX IF NOT EXISTS idx_hw_sub_student  ON homework_submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_income_linked_canteen ON income_records(linked_canteen_payment_id);
CREATE INDEX IF NOT EXISTS idx_income_linked_pay ON income_records(linked_payment_id);
CREATE INDEX IF NOT EXISTS idx_income_term ON income_records(term_id);
CREATE INDEX IF NOT EXISTS idx_income_txn_date ON income_records(transaction_date);
CREATE INDEX IF NOT EXISTS idx_intents_status ON payment_intents(status);
CREATE INDEX IF NOT EXISTS idx_intents_student ON payment_intents(student_id);
CREATE INDEX IF NOT EXISTS idx_leave_staff ON leave_requests(staff_id, status);
CREATE INDEX IF NOT EXISTS idx_messages_thread  ON messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON sync_outbox(synced_at, dead, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_outbox_unsynced ON sync_outbox(synced_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_parents_phone ON parents(phone) WHERE phone IS NOT NULL AND phone != '';
CREATE INDEX IF NOT EXISTS idx_payments_student ON payments(student_id);
CREATE INDEX IF NOT EXISTS idx_pwreset_status ON password_reset_requests(status);
CREATE INDEX IF NOT EXISTS idx_pwreset_user   ON password_reset_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_receipts_number ON receipts(receipt_number);
CREATE INDEX IF NOT EXISTS idx_receipts_source ON receipts(source, source_id);
CREATE INDEX IF NOT EXISTS idx_school_calendar_date ON school_calendar(date);
CREATE INDEX IF NOT EXISTS idx_scores_student_term ON scores(student_id, term_id);
CREATE INDEX IF NOT EXISTS idx_staff_attendance ON staff_attendance(staff_id, date);
CREATE INDEX IF NOT EXISTS idx_student_attendance ON student_attendance(student_id, date);
CREATE INDEX IF NOT EXISTS idx_students_class ON students(current_class_id);
CREATE INDEX IF NOT EXISTS idx_students_status ON students(status);
CREATE INDEX IF NOT EXISTS idx_system_log_created ON system_log(created_at);
CREATE INDEX IF NOT EXISTS idx_threads_parent   ON message_threads(parent_id);
CREATE INDEX IF NOT EXISTS idx_transport_pay_term    ON transport_payments(term_id, student_id);
CREATE INDEX IF NOT EXISTS idx_transport_stops_route ON transport_stops(route_id);
CREATE INDEX IF NOT EXISTS idx_tt_entries_class   ON timetable_entries(class_group_id);
CREATE INDEX IF NOT EXISTS idx_tt_entries_teacher ON timetable_entries(teacher_id);
CREATE INDEX IF NOT EXISTS idx_wb_import_sheet ON workbook_import_log(sheet, imported_at);
