#!/usr/bin/env node
// Nickland Edusoft — the preload script, made loadable.
// Copyright © 2026 Nickland Sales. All rights reserved.
//
// Electron runs a preload script SANDBOXED, and a sandboxed preload's
// `require()` resolves electron and a handful of built-ins and nothing else.
// It cannot load a file next to it. So this:
//
//     const { buildApi } = require('./api-surface');
//
// fails at run time with "module not found: ./api-surface" — the whole preload
// is dropped, `window.api` never appears, and the application starts with no
// way to reach its own database. That is precisely what happened, and it did
// not show up in any test because a test can require the file perfectly well;
// only Electron's sandbox cannot.
//
// The fix is not to weaken the sandbox and it is not to keep a second copy of
// four hundred channels in the preload. It is to give Electron a preload with
// nothing to resolve: esbuild inlines the surface, and what ships is one file
// that requires only `electron`.
//
//   electron/preload.js         what a developer edits
//   electron/preload.bundle.js  what Electron loads — generated, never edited
//
// Every script that runs or packages the application builds this first (see
// the `pre` hooks in package.json), so there is no path to an application
// without it.

import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const entry = path.join(repo, 'electron', 'preload.js');
const out = path.join(repo, 'electron', 'preload.bundle.js');

await build({
  entryPoints: [entry],
  outfile: out,
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node18',
  // The one thing a sandboxed preload CAN require, and the one thing that must
  // not be inlined.
  external: ['electron'],
  banner: {
    js: '// GENERATED by scripts/build-preload.mjs — do not edit.\n' +
        '// Source: electron/preload.js + electron/api-surface.js\n',
  },
});

const code = fs.readFileSync(out, 'utf8');

// The whole point, asserted rather than hoped for: nothing left to resolve.
const stray = [...code.matchAll(/require\(["']([^"']+)["']\)/g)]
  .map(m => m[1])
  .filter(name => name !== 'electron');
if (stray.length) {
  console.error(
    `\n✖ The bundled preload still requires ${stray.map(s => `"${s}"`).join(', ')}.\n` +
    '  A sandboxed preload can only require "electron", so Electron would drop\n' +
    '  the whole script and the application would start with no window.api.\n'
  );
  process.exit(1);
}

console.log(`✓ Preload bundled — ${(code.length / 1024).toFixed(1)} KB in ${path.relative(repo, out)}`);
